# Compte Rendu BE Météo #

## ALBRECHT Niels ##

## POURÉ Thomas ##

## RAMILISON Hugo ##

Import des librairies : 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Téléchargement des données : 

In [2]:
data = pd.read_csv("./data/donnees-synop-essentielles-omm.csv", sep=";")
data.head()

ID OMM station                       Date  Pression au niveau mer  \
0            7181  2016-07-12T11:00:00+02:00                101410.0   
1           81405  2017-01-08T07:00:00+01:00                101140.0   
2            7627  2017-01-08T13:00:00+01:00                103380.0   
3           78894  2017-01-09T13:00:00+01:00                101760.0   
4            7020  2017-01-12T13:00:00+01:00                100580.0   

   Variation de pression en 3 heures  Type de tendance barométrique  \
0                              -30.0                            8.0   
1                             -140.0                            8.0   
2                              -40.0                            8.0   
3                                0.0                            NaN   
4                             -710.0                            8.0   

   Direction du vent moyen 10 mn  Vitesse du vent moyen 10 mn  Température  \
0                          230.0                          2.9       293.35   
1                          240.0                          0.5       297.25   
2                           30.0                          2.1       277.55   
3                          100.0                          2.3       298.15   
4                          210.0                         11.9       282.05   

   Point de rosée  Humidité  ...  Altitude          communes (name)  \
0          286.55      65.0  ...       336  Thuilley-aux-Groseilles   
1          296.25      94.0  ...         4                  Matoury   
2          269.75      57.0  ...       414         Lorp-Sentaraille   
3          291.35      66.0  ...        44                      NaN   
4          280.15      88.0  ...         6                 La Hague   

   communes (code)                               EPCI (name)  EPCI (code)  \
0            54523  CC du Pays de Colombey et du Sud Toulois  245400510.0   
1            97307                     CA du Centre Littoral  249730045.0   
2            09289                     CC Couserans-Pyrénées  200067940.0   
3              NaN                                       NaN          NaN   
4            50041                            CA du Cotentin  200067205.0   

    department (name)  department (code)  region (name)  region (code)  \
0  Meurthe-et-Moselle                 54      Grand Est           44.0   
1              Guyane                973         Guyane            3.0   
2              Ariège                 09      Occitanie           76.0   
3                 NaN                NaN            NaN            NaN   
4              Manche                 50      Normandie           28.0   

   mois_de_l_annee  
0                7  
1                1  
2                1  
3                1  
4                1  

[5 rows x 82 columns]

On va découper les données par station afin de les manipuler plus simplement =
- Le fichier data/stations.csv liste les stations avec leurs info géographiques
- Le dossier data/mesures/ contient les fichiers csv des mesures réalisées par stations (un fichier par station)

In [4]:
#table listant les stations ainsi que leurs infos fixe (nom, localisation, etc...)

station_cols =   [
    "ID OMM station", "Nom", "Coordonnees", "Latitude", "Longitude", "Altitude",
    "communes (name)", "communes (code)",
    "EPCI (name)", "EPCI (code)",
    "department (name)", "department (code)",
    "region (name)", "region (code)"
]

stations = data[station_cols].drop_duplicates(subset="ID OMM station")

stations.to_csv("./data/stations.csv", index=False)
print(f"table des stations enregistrée : {stations.shape[0]} stations uniques")


table des stations enregistrée : 62 stations uniques


In [5]:
#Créations des tables et csv des mesures pour chaques stations

measure_cols = [col for col in data.columns if col not in station_cols]

for station_id in stations["ID OMM station"]:
    station_data = data.loc[data["ID OMM station"] == station_id, measure_cols]
    
    filename = f"data/mesures/station_{station_id}.csv"
    station_data.to_csv(filename, index=False)

print("Fichiers de mesures créés (sans données géographiques) dans data/mesures/")

Fichiers de mesures créés (sans données géographiques) dans data/mesures/


In [ ]:
extract = True
n_extract = 10
if extract :
    # select some stations
    stations = data["ID OMM station"]
    stations_unique = np.unique(stations)
    chosen = np.random.choice(len(stations_unique), n_extract)
    print(chosen)
    print(stations_unique)
    chosen_stations = stations_unique[chosen]
    print(chosen_stations)
    # extract stations
    extracted_df = data.loc[data["ID OMM station"].isin(chosen_stations)]
    # save to csv
    extracted_df.to_csv(f"./data/donnees_extracted_{n_extract}.csv", index=False)  


[ 5 30 42 15 37 53 60 32 48 49]
[ 7005  7015  7020  7027  7037  7072  7110  7117  7130  7139  7149  7168
  7181  7190  7207  7222  7240  7255  7280  7299  7314  7335  7434  7460
  7471  7481  7510  7535  7558  7577  7591  7607  7621  7627  7630  7643
  7650  7661  7690  7747  7761  7790 61968 61970 61972 61976 61980 61996
 61997 61998 67005 71805 78890 78894 78897 78922 78925 81401 81405 81408
 81415 89642]
[ 7072  7591 61968  7222  7661 78894 81415  7621 61997 61998]


In [ ]:
# le même extract, mais en filtrant les dom-toms
extract = True
n_extract = 20
if extract :
    # select some stations
    stations = data["ID OMM station"]
    stations_unique = np.unique(stations[stations < 10000])
    chosen = np.random.choice(len(stations_unique), n_extract)
    print(chosen)
    print(stations_unique)
    chosen_stations = stations_unique[chosen]
    print(chosen_stations)
    # extract stations
    extracted_df = data.loc[data["ID OMM station"].isin(chosen_stations)]
    # save to csv
    extracted_df.to_csv(f"./data/donnees_extracted_metro_{n_extract}.csv", index=False)  

[37  7 20 22 30  9 36 18 41 38 37 10 22 14 29  2 26 26 27  7]
[7005 7015 7020 7027 7037 7072 7110 7117 7130 7139 7149 7168 7181 7190
 7207 7222 7240 7255 7280 7299 7314 7335 7434 7460 7471 7481 7510 7535
 7558 7577 7591 7607 7621 7627 7630 7643 7650 7661 7690 7747 7761 7790]
[7661 7117 7314 7434 7591 7139 7650 7280 7790 7690 7661 7149 7434 7207
 7577 7020 7510 7510 7535 7117]


In [3]:
# toutes les stations, en filtrant les dom-toms
extract = True
if extract :
    # select some stations
    stations = data["ID OMM station"]
    stations_unique = np.unique(stations[stations < 10000])
    chosen_stations = stations_unique
    print(chosen_stations)
    # extract stations
    extracted_df = data.loc[data["ID OMM station"].isin(chosen_stations)]
    # save to csv
    extracted_df.to_csv(f"./data/donnees_extracted_metro_all.csv", index=False)  

[7005 7015 7020 7027 7037 7072 7110 7117 7130 7139 7149 7168 7181 7190
 7207 7222 7240 7255 7280 7299 7314 7335 7434 7460 7471 7481 7510 7535
 7558 7577 7591 7607 7621 7627 7630 7643 7650 7661 7690 7747 7761 7790]
